### ISSUE TITLE
STM8: cycles take less time than on real hardware ?

### ISSUE THREAD

**Issue by dzid26** [danieldrotos/ucsim#2]
Command:
`ucsim_stm8 -t stm8s105 bin/main`

So I have this [calculation](https://github.com/dzid26/TSDZ2-Smart-EBike/blob/75bb799140821cf19ce882d93104a3443c59d1c3/src/main.c#L85-L86) that compares expected cycles time (delay_us) to actual time observed (`isr_load_delta_tim`) and uses that to calculate isr cpu load %.

The delay function cycles was tuned on the hardware and compared to the timer.  Effectively this function nicely computes isr load when the delay takes longer than expected. 

However on in the simulator, the `isr_load_delta_tim` is _shorter_ than expected `delay_us(MEAS_WINDOW)`.

Why would that be?

If I look into TIM3 register, the prescaler (0x06) and period (0xff	0xff) seem to match the hardware:
(ucsim)
```
> dump 0x5320
0x05320                                01 00 01 00 00 00 00 00 ........
0x05328                                2e 53 06 ff ff 00 00 00 .S......
```
(stm8 gdb)
```-exec x/16xb 0x5320
0x5320:	0x01	0x00	0x07	0x00	0x00	0x00	0x00	0x00
0x5328:	0x46	0x08	0x06	0xff	0xff	0x00	0x00	0x00
```

`HSIPrescaler` in simulator also matches code settings as expected.

**Comment by danieldrotos** [comment]
Pipeline behaviour of stm8 is not simulated, and simulation is based on instructions instead of clocks. So simulation will never be clock accurate.
